### ISSUE TITLE
Проблемы с игрой на macOS 10.12.6

### ISSUE THREAD

**Issue by Valeriy-Zainullin** [vaniacer/piu-piu-SH#11]
![default](https://user-images.githubusercontent.com/16137770/31236554-14b88ebe-a9fd-11e7-82e7-706d6098045c.png)
В терминале куча нечитаемого текста и меню. При этом сама игра не работает - навигация по меню не осуществляется.

**Comment by vaniacer** [comment]
Мак мне не доступен, сам не проверял но говорят, чтобы заработало на MacOS нужно установить bash v4:
brew update && brew install bash

**Comment by Valeriy-Zainullin** [comment]
Спасибо
