### ISSUE TITLE
feedback that you got hit

### ISSUE THREAD

**Issue by kilobyte** [vaniacer/piu-piu-SH#15]
The hitbox of the helicopter is quite unobvious.  It's somewhat hard to notice when you get and when you don't get hit — the only way is to watch that small "Lives" number in the top line.  Thus, it'd be nice if the player's sprite reacted somehow: make it "wince", show an explosion, something of this kind.

**Comment by vaniacer** [comment]
Ok I'll think something.

**Comment by vaniacer** [comment]
Add a lot of explosions when player got hit to make it more obvious.
