### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by RottenRonnie** [vaniacer/piu-piu-SH#19]
I'm a new enough user to need install instructions for a debian based distro.

**Comment by umutkacar** [comment]
@RottenRonnie there you go;
`git clone https://github.com/vaniacer/piu-piu-SH.git`
`cd piu-piu-SH`
`./piu-piu`

**Comment by RottenRonnie** [comment]
That will teach me not to list or cat the files. 

Thank you.
