### ISSUE TITLE
The game should check bash version

### ISSUE THREAD

**Issue by Self-Perfection** [vaniacer/piu-piu-SH#8]
What is the minimum bash version required for this game to work?

I suppose you should check `${BASH_VERSINFO[@]}` on startup and stop with error message if too old bash version is used.

**Comment by vaniacer** [comment]
To tell you the truth [i don't know)](http://coub.com/view/jqt2i20) So i don't bother to check bash version.
I'm using 4.3.

**Comment by vaniacer** [comment]
Yes you are right. Added.
